In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv('clean_rainfall_dataframe.csv')
data.head()

Year  Station  Month  Day  Rainfall  AvgHumidity  AvgTemp  StationIndex  \
0  1970  Barisal      1    1         0           78     16.2             2   
1  1970  Barisal      1    2         0           78     16.3             2   
2  1970  Barisal      1    3         0           81     16.4             2   
3  1970  Barisal      1    4         0           79     16.9             2   
4  1970  Barisal      1    5         0           80     17.2             2   

   class  label  
0      0    0.0  
1      0    0.0  
2      0    0.0  
3      0    0.0  
4      0    0.0

In [2]:
data = data.drop(['Station','class', 'label'], axis=1)
data.head()

Year  Month  Day  Rainfall  AvgHumidity  AvgTemp  StationIndex
0  1970      1    1         0           78     16.2             2
1  1970      1    2         0           78     16.3             2
2  1970      1    3         0           81     16.4             2
3  1970      1    4         0           79     16.9             2
4  1970      1    5         0           80     17.2             2

In [3]:
X = data.drop(['Rainfall'], axis=1)
y = data['Rainfall']

X.head()

Year  Month  Day  AvgHumidity  AvgTemp  StationIndex
0  1970      1    1           78     16.2             2
1  1970      1    2           78     16.3             2
2  1970      1    3           81     16.4             2
3  1970      1    4           79     16.9             2
4  1970      1    5           80     17.2             2

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)


In [5]:
#print(type(X_train['Year']))
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = gnb.predict(X_test)
#print(y_pred)

In [6]:
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


Accuracy: 0.6894918560922078


In [13]:
from sklearn.svm import LinearSVC
svc_model = LinearSVC(random_state=0)

pred = svc_model.fit(X_train, y_train).predict(X_test)
#print the accuracy score of the model
print("LinearSVC accuracy : ",metrics.accuracy_score(y_test, pred, normalize = True))

KeyboardInterrupt: 

In [14]:
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors=3)
#Train the algorithm
neigh.fit(X_train, y_train)
# predict the response 
pred = neigh.predict(X_test)
# evaluate accuracy
print ("KNeighbors accuracy score : ",metrics.accuracy_score(y_test, pred))

KNeighbors accuracy score :  0.6667479560010782


In [15]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))


/home/akash/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/akash/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:459: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Accuracy of logistic regression classifier on test set: 0.69


In [16]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[107908     90      0 ...      0      0      0]
 [  5348      3      0 ...      0      0      0]
 [  3633      2      0 ...      0      0      0]
 ...
 [     1      0      0 ...      0      0      0]
 [     1      0      0 ...      0      0      0]
 [     1      0      0 ...      0      0      0]]


In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      1.00      0.82    107998
           1       0.02      0.00      0.00      5351
           2       0.00      0.00      0.00      3635
           3       0.00      0.00      0.00      2970
           4       0.00      0.00      0.00      2426
           5       0.00      0.00      0.00      2092
           6       0.00      0.00      0.00      1870
           7       0.00      0.00      0.00      1574
           8       0.00      0.00      0.00      1469
           9       0.00      0.00      0.00      1280
          10       0.00      0.00      0.00      1317
          11       0.00      0.00      0.00      1136
          12       0.00      0.00      0.00      1096
          13       0.00      0.00      0.00       974
          14       0.00      0.00      0.00       905
          15       0.00      0.00      0.00       934
          16       0.00      0.00      0.00       778
          17       0.00    

/home/akash/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [7]:
# from sklearn.metrics import roc_auc_score
# from sklearn.metrics import roc_curve
# logit_roc_auc = roc_auc_score(y_test, logreg.predict(X_test))
# fpr, tpr, thresholds = roc_curve(y_test, logreg.predict_proba(X_test)[:,1])
# plt.figure()
# plt.plot(fpr, tpr, label='Logistic Regression (area = %0.2f)' % logit_roc_auc)
# plt.plot([0, 1], [0, 1],'r--')
# plt.xlim([0.0, 1.0])
# plt.ylim([0.0, 1.05])
# plt.xlabel('False Positive Rate')
# plt.ylabel('True Positive Rate')
# plt.title('Receiver operating characteristic')
# plt.legend(loc="lower right")
# plt.savefig('Log_ROC')
# plt.show()

In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
linreg = LinearRegression(fit_intercept=False)
linreg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None,
         normalize=False)

In [9]:
y_pred = linreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(linreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.06
